"""init

Revision ID: e46dc3f1cd7b
Revises:
Create Date: 2023-04-25 12:39:18.269715

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "e46dc3f1cd7b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metricsunit",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("service_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("response_time_ms", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_metricsunit_path"), "metricsunit", ["path"], unique=False)
    op.create_index(op.f("ix_metricsunit_service_name"), "metricsunit", ["service_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_metricsunit_service_name"), table_name="metricsunit")
    op.drop_index(op.f("ix_metricsunit_path"), table_name="metricsunit")
    op.drop_table("metricsunit")
    # ### end Alembic commands ###
